"""
backend/models/user.py
──────────────────────
SQLAlchemy ORM model for Users.

Stores authentication data, role, and org affiliation.
Rich profile data (preferences, analytics) lives in MongoDB.

Relationships:
  User  ──< Resume       (one user has many resumes)
  User  ──< AuditLog     (one user generates many audit events)
  Org   ──< User         (many users per organization, HR team)

Roles:
  STUDENT  → can upload resumes, view own analysis
  HR       → can create JDs, view all candidates, rank
  ADMIN    → full platform access
"""

from __future__ import annotations

import enum
from datetime import datetime, timezone

from sqlalchemy import Boolean, DateTime, Enum, ForeignKey, Index, String, text
from sqlalchemy.dialects.postgresql import UUID as PG_UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from db.postgres import Base


class UserRole(str, enum.Enum):
    """
    User role enum.
    str mixin means values are plain strings in DB (not integers).
    FastAPI / Pydantic can serialize these directly.
    """
    STUDENT = "STUDENT"
    HR      = "HR"
    ADMIN   = "ADMIN"


class User(Base):
    """
    Core user table. Stores authentication + role only.

    Design decisions:
    - UUID primary key: avoids sequential ID enumeration attacks
    - password_hash: bcrypt via passlib (cost factor 12)
    - is_active: soft delete — deactivated users can't login
    - org_id: nullable FK — students don't belong to an org
    """

    __tablename__ = "users"

    # ── Identity ──────────────────────────────────────────────────────────────
    id: Mapped[str] = mapped_column(
        PG_UUID(as_uuid=False),
        primary_key=True,
        server_default=text("gen_random_uuid()"),
        comment="UUID v4, generated by PostgreSQL",
    )
    email: Mapped[str] = mapped_column(
        String(255),
        unique=True,
        nullable=False,
        index=True,
        comment="User email, used as login identifier",
    )
    password_hash: Mapped[str] = mapped_column(
        String(255),
        nullable=False,
        comment="bcrypt hash of the user password",
    )

    # ── Profile ───────────────────────────────────────────────────────────────
    full_name: Mapped[str | None] = mapped_column(String(255))
    phone: Mapped[str | None] = mapped_column(String(20))
    avatar_url: Mapped[str | None] = mapped_column(String(1000))

    # ── Authorization ─────────────────────────────────────────────────────────
    role: Mapped[UserRole] = mapped_column(
        Enum(UserRole, name="user_role_enum"),
        nullable=False,
        default=UserRole.STUDENT,
        server_default="STUDENT",
        comment="RBAC role",
    )

    # ── Organization (HR users belong to an org) ──────────────────────────────
    org_id: Mapped[str | None] = mapped_column(
        PG_UUID(as_uuid=False),
        ForeignKey("organizations.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
    )

    # ── Account State ─────────────────────────────────────────────────────────
    is_active: Mapped[bool] = mapped_column(
        Boolean,
        nullable=False,
        default=True,
        server_default="true",
        comment="Soft delete: False = account deactivated",
    )
    is_email_verified: Mapped[bool] = mapped_column(
        Boolean, nullable=False, default=False, server_default="false"
    )
    email_verification_token: Mapped[str | None] = mapped_column(String(255))

    # ── Timestamps ────────────────────────────────────────────────────────────
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=text("NOW()"),
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=text("NOW()"),
        onupdate=lambda: datetime.now(timezone.utc),
    )
    last_login_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))

    # ── Password Reset ────────────────────────────────────────────────────────
    password_reset_token: Mapped[str | None] = mapped_column(String(255))
    password_reset_expires_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True)
    )

    # ── Relationships ─────────────────────────────────────────────────────────
    resumes: Mapped[list["Resume"]] = relationship(   # type: ignore[name-defined]
        "Resume",
        back_populates="user",
        cascade="all, delete-orphan",
        lazy="select",
    )
    org: Mapped["Organization | None"] = relationship(  # type: ignore[name-defined]
        "Organization",
        back_populates="members",
        lazy="select",
    )

    # ── Indexes ───────────────────────────────────────────────────────────────
    __table_args__ = (
        Index("ix_users_email_active", "email", "is_active"),
        Index("ix_users_org_role", "org_id", "role"),
        {"comment": "Platform users — students and HR managers"},
    )

    def __repr__(self) -> str:
        return f"<User id={self.id!r} email={self.email!r} role={self.role}>"

    @property
    def is_hr(self) -> bool:
        return self.role == UserRole.HR

    @property
    def is_admin(self) -> bool:
        return self.role == UserRole.ADMIN

    @property
    def is_student(self) -> bool:
        return self.role == UserRole.STUDENT


class Organization(Base):
    """
    HR organization (company / institution).
    Multiple HR users can belong to the same org.
    """

    __tablename__ = "organizations"

    id: Mapped[str] = mapped_column(
        PG_UUID(as_uuid=False), primary_key=True, server_default=text("gen_random_uuid()")
    )
    name: Mapped[str] = mapped_column(String(255), nullable=False)
    domain: Mapped[str | None] = mapped_column(
        String(255),
        comment="Email domain for auto-org-assignment (e.g. google.com)",
    )
    logo_url: Mapped[str | None] = mapped_column(String(1000))
    is_active: Mapped[bool] = mapped_column(Boolean, default=True, server_default="true")
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=text("NOW()")
    )

    # ── Relationships ─────────────────────────────────────────────────────────
    members: Mapped[list[User]] = relationship(
        "User", back_populates="org", lazy="select"
    )
    internships: Mapped[list["Internship"]] = relationship(  # type: ignore[name-defined]
        "Internship", back_populates="org", lazy="select"
    )

    def __repr__(self) -> str:
        return f"<Organization id={self.id!r} name={self.name!r}>"