"""Add application events and other tables

Revision ID: 7f5d26d875c1
Revises: 003_ranking_engine_fields
Create Date: 2026-07-06 16:16:09.180560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7f5d26d875c1'
down_revision: Union[str, None] = '003_ranking_engine_fields'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Create enum types manually if they do not exist
    connection = op.get_bind()
    res = connection.execute(sa.text("SELECT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'internship_status');"))
    if not res.scalar():
        op.execute("CREATE TYPE internship_status AS ENUM ('DRAFT', 'PUBLISHED', 'CLOSED', 'ARCHIVED');")
    res2 = connection.execute(sa.text("SELECT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'work_mode');"))
    if not res2.scalar():
        op.execute("CREATE TYPE work_mode AS ENUM ('REMOTE', 'HYBRID', 'ONSITE');")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('from_status', sa.String(length=50), nullable=True),
    sa.Column('to_status', sa.String(length=50), nullable=True),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('actor_role', sa.String(length=20), nullable=True),
    sa.Column('event_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_application_events_actor_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name=op.f('fk_application_events_application_id_applications'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_application_events'))
    )
    op.alter_column('activity_logs', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('application_mappings', 'combined_risk_level',
               existing_type=postgresql.ENUM('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='risk_level'),
               nullable=False,
               existing_server_default=sa.text("'LOW'::risk_level"))
    op.drop_constraint(op.f('application_mappings_application_id_key'), 'application_mappings', type_='unique')
    op.drop_constraint(op.f('application_mappings_ats_resume_uuid_key'), 'application_mappings', type_='unique')
    op.drop_constraint(op.f('application_mappings_interview_session_uuid_key'), 'application_mappings', type_='unique')
    op.drop_constraint(op.f('application_mappings_simulation_application_id_key'), 'application_mappings', type_='unique')
    op.drop_constraint(op.f('application_mappings_simulation_attempt_id_key'), 'application_mappings', type_='unique')
    op.drop_index(op.f('idx_application_mappings_attempt'), table_name='application_mappings')
    op.create_unique_constraint(op.f('uq_application_mappings_application_id'), 'application_mappings', ['application_id'])
    op.create_unique_constraint(op.f('uq_application_mappings_ats_resume_uuid'), 'application_mappings', ['ats_resume_uuid'])
    op.create_unique_constraint(op.f('uq_application_mappings_interview_session_uuid'), 'application_mappings', ['interview_session_uuid'])
    op.create_unique_constraint(op.f('uq_application_mappings_simulation_application_id'), 'application_mappings', ['simulation_application_id'])
    op.create_unique_constraint(op.f('uq_application_mappings_simulation_attempt_id'), 'application_mappings', ['simulation_attempt_id'])
    op.add_column('applications', sa.Column('cover_letter', sa.Text(), nullable=True))
    op.add_column('applications', sa.Column('resume_url', sa.String(length=512), nullable=True))
    op.add_column('applications', sa.Column('withdrawn_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('applications', sa.Column('hired_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('applications', sa.Column('rejection_reason', sa.Text(), nullable=True))
    op.drop_index(op.f('idx_applications_candidate'), table_name='applications', postgresql_where='(deleted_at IS NULL)')
    op.drop_index(op.f('idx_applications_status'), table_name='applications', postgresql_where='(deleted_at IS NULL)')
    op.drop_index(op.f('idx_applications_vacancy'), table_name='applications', postgresql_where='(deleted_at IS NULL)')
    op.drop_index(op.f('uq_candidate_vacancy_active'), table_name='applications', postgresql_where='(deleted_at IS NULL)')
    op.alter_column('ats_results', 'matched_skills',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               type_=sa.ARRAY(sa.String()),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::text[]"))
    op.alter_column('ats_results', 'missing_skills',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               type_=sa.ARRAY(sa.String()),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::text[]"))
    op.alter_column('ats_results', 'fraud_probability',
               existing_type=sa.NUMERIC(precision=5, scale=4),
               nullable=False,
               existing_server_default=sa.text('0.0'))
    op.drop_constraint(op.f('ats_results_application_id_key'), 'ats_results', type_='unique')
    op.create_unique_constraint(op.f('uq_ats_results_application_id'), 'ats_results', ['application_id'])
    op.drop_constraint(op.f('candidate_mappings_ats_user_uuid_key'), 'candidate_mappings', type_='unique')
    op.drop_constraint(op.f('candidate_mappings_capvia_candidate_uuid_key'), 'candidate_mappings', type_='unique')
    op.drop_constraint(op.f('candidate_mappings_interview_candidate_uuid_key'), 'candidate_mappings', type_='unique')
    op.drop_constraint(op.f('candidate_mappings_simulation_candidate_id_key'), 'candidate_mappings', type_='unique')
    op.drop_index(op.f('idx_candidate_mappings_simulation'), table_name='candidate_mappings')
    op.create_unique_constraint(op.f('uq_candidate_mappings_ats_user_uuid'), 'candidate_mappings', ['ats_user_uuid'])
    op.create_unique_constraint(op.f('uq_candidate_mappings_capvia_candidate_uuid'), 'candidate_mappings', ['capvia_candidate_uuid'])
    op.create_unique_constraint(op.f('uq_candidate_mappings_interview_candidate_uuid'), 'candidate_mappings', ['interview_candidate_uuid'])
    op.create_unique_constraint(op.f('uq_candidate_mappings_simulation_candidate_id'), 'candidate_mappings', ['simulation_candidate_id'])
    op.alter_column('companies', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_constraint(op.f('companies_name_key'), 'companies', type_='unique')
    op.drop_index(op.f('idx_companies_created_by'), table_name='companies')
    op.drop_index(op.f('uq_companies_name_active'), table_name='companies', postgresql_where='(deleted_at IS NULL)')
    op.create_unique_constraint(op.f('uq_companies_name'), 'companies', ['name'])
    op.drop_index(op.f('idx_company_members_company'), table_name='company_members')
    op.drop_index(op.f('idx_company_members_user'), table_name='company_members')
    op.drop_constraint(op.f('uq_company_member'), 'company_members', type_='unique')
    op.drop_constraint(op.f('dna_profiles_application_id_key'), 'dna_profiles', type_='unique')
    op.create_unique_constraint(op.f('uq_dna_profiles_application_id'), 'dna_profiles', ['application_id'])
    op.drop_constraint(op.f('integrity_results_application_id_key'), 'integrity_results', type_='unique')
    op.create_unique_constraint(op.f('uq_integrity_results_application_id'), 'integrity_results', ['application_id'])
    op.add_column('internships', sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'CLOSED', 'ARCHIVED', name='internship_status'), nullable=False))
    op.add_column('internships', sa.Column('published_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('internships', sa.Column('work_mode', sa.Enum('REMOTE', 'HYBRID', 'ONSITE', name='work_mode'), nullable=False))
    op.add_column('internships', sa.Column('location', sa.String(length=255), nullable=True))
    op.add_column('internships', sa.Column('duration_weeks', sa.Integer(), nullable=True))
    op.add_column('internships', sa.Column('stipend_min', sa.Integer(), nullable=True))
    op.add_column('internships', sa.Column('stipend_max', sa.Integer(), nullable=True))
    op.add_column('internships', sa.Column('stipend_currency', sa.String(length=10), nullable=False))
    op.add_column('internships', sa.Column('openings', sa.Integer(), nullable=False))
    op.add_column('internships', sa.Column('application_limit', sa.Integer(), nullable=True))
    op.add_column('internships', sa.Column('application_deadline', sa.Date(), nullable=True))
    op.add_column('internships', sa.Column('view_count', sa.Integer(), nullable=False))
    op.add_column('internships', sa.Column('created_by', sa.UUID(), nullable=True))
    op.add_column('internships', sa.Column('updated_by', sa.UUID(), nullable=True))
    op.add_column('internships', sa.Column('slug', sa.String(length=300), nullable=True))
    op.alter_column('internships', 'responsibilities',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               type_=sa.ARRAY(sa.String()),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::text[]"))
    op.alter_column('internships', 'required_skills',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               type_=sa.ARRAY(sa.String()),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::text[]"))
    op.alter_column('internships', 'technologies',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               type_=sa.ARRAY(sa.String()),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::text[]"))
    op.drop_index(op.f('idx_internships_company'), table_name='internships', postgresql_where='(deleted_at IS NULL)')
    op.create_foreign_key(op.f('fk_internships_created_by_users'), 'internships', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_internships_updated_by_users'), 'internships', 'users', ['updated_by'], ['id'], ondelete='SET NULL')
    op.alter_column('interview_results', 'strengths',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               type_=sa.ARRAY(sa.String()),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::text[]"))
    op.alter_column('interview_results', 'improvements',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               type_=sa.ARRAY(sa.String()),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::text[]"))
    op.drop_constraint(op.f('interview_results_application_id_key'), 'interview_results', type_='unique')
    op.drop_constraint(op.f('interview_results_session_id_key'), 'interview_results', type_='unique')
    op.create_unique_constraint(op.f('uq_interview_results_application_id'), 'interview_results', ['application_id'])
    op.create_unique_constraint(op.f('uq_interview_results_session_id'), 'interview_results', ['session_id'])
    op.alter_column('notifications', 'message',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_index(op.f('idx_notifications_user_unread'), table_name='notifications', postgresql_where='(is_read = false)')
    op.drop_index(op.f('idx_rankings_internship_rank'), table_name='rankings', postgresql_where='(deleted_at IS NULL)')
    op.drop_index(op.f('idx_rankings_internship_score'), table_name='rankings', postgresql_where='(deleted_at IS NULL)')
    op.drop_index(op.f('idx_rankings_top_candidates'), table_name='rankings', postgresql_where='((is_top_candidate = true) AND (deleted_at IS NULL))')
    op.drop_constraint(op.f('rankings_application_id_key'), 'rankings', type_='unique')
    op.create_unique_constraint(op.f('uq_rankings_application_id'), 'rankings', ['application_id'])
    op.alter_column('reports', 'summary',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('reports', 'strengths',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               type_=sa.ARRAY(sa.String()),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::text[]"))
    op.alter_column('reports', 'weaknesses',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               type_=sa.ARRAY(sa.String()),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::text[]"))
    op.alter_column('reports', 'recommendations',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               type_=sa.ARRAY(sa.String()),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::text[]"))
    op.drop_constraint(op.f('reports_application_id_key'), 'reports', type_='unique')
    op.create_unique_constraint(op.f('uq_reports_application_id'), 'reports', ['application_id'])
    op.alter_column('simulation_results', 'ai_dependency_score',
               existing_type=sa.NUMERIC(precision=3, scale=2),
               nullable=False,
               existing_server_default=sa.text('0.0'))
    op.drop_constraint(op.f('simulation_results_application_id_key'), 'simulation_results', type_='unique')
    op.drop_constraint(op.f('simulation_results_attempt_id_key'), 'simulation_results', type_='unique')
    op.create_unique_constraint(op.f('uq_simulation_results_application_id'), 'simulation_results', ['application_id'])
    op.create_unique_constraint(op.f('uq_simulation_results_attempt_id'), 'simulation_results', ['attempt_id'])
    op.drop_index(op.f('idx_user_sessions_token'), table_name='user_sessions')
    op.drop_index(op.f('idx_user_sessions_user'), table_name='user_sessions')
    op.drop_constraint(op.f('user_sessions_refresh_token_hash_key'), 'user_sessions', type_='unique')
    op.create_unique_constraint(op.f('uq_user_sessions_refresh_token_hash'), 'user_sessions', ['refresh_token_hash'])
    op.drop_index(op.f('uq_users_email_active'), table_name='users', postgresql_where='(deleted_at IS NULL)')
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_unique_constraint(op.f('uq_users_email'), 'users', ['email'])
    op.drop_index(op.f('idx_vacancy_mappings_simulation'), table_name='vacancy_mappings')
    op.drop_constraint(op.f('vacancy_mappings_ats_jd_uuid_key'), 'vacancy_mappings', type_='unique')
    op.drop_constraint(op.f('vacancy_mappings_capvia_vacancy_uuid_key'), 'vacancy_mappings', type_='unique')
    op.drop_constraint(op.f('vacancy_mappings_simulation_internship_id_key'), 'vacancy_mappings', type_='unique')
    op.create_unique_constraint(op.f('uq_vacancy_mappings_ats_jd_uuid'), 'vacancy_mappings', ['ats_jd_uuid'])
    op.create_unique_constraint(op.f('uq_vacancy_mappings_capvia_vacancy_uuid'), 'vacancy_mappings', ['capvia_vacancy_uuid'])
    op.create_unique_constraint(op.f('uq_vacancy_mappings_simulation_internship_id'), 'vacancy_mappings', ['simulation_internship_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_vacancy_mappings_simulation_internship_id'), 'vacancy_mappings', type_='unique')
    op.drop_constraint(op.f('uq_vacancy_mappings_capvia_vacancy_uuid'), 'vacancy_mappings', type_='unique')
    op.drop_constraint(op.f('uq_vacancy_mappings_ats_jd_uuid'), 'vacancy_mappings', type_='unique')
    op.create_unique_constraint(op.f('vacancy_mappings_simulation_internship_id_key'), 'vacancy_mappings', ['simulation_internship_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('vacancy_mappings_capvia_vacancy_uuid_key'), 'vacancy_mappings', ['capvia_vacancy_uuid'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('vacancy_mappings_ats_jd_uuid_key'), 'vacancy_mappings', ['ats_jd_uuid'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_vacancy_mappings_simulation'), 'vacancy_mappings', ['simulation_internship_id'], unique=False)
    op.drop_constraint(op.f('uq_users_email'), 'users', type_='unique')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('uq_users_email_active'), 'users', ['email'], unique=True, postgresql_where='(deleted_at IS NULL)')
    op.drop_constraint(op.f('uq_user_sessions_refresh_token_hash'), 'user_sessions', type_='unique')
    op.create_unique_constraint(op.f('user_sessions_refresh_token_hash_key'), 'user_sessions', ['refresh_token_hash'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_user_sessions_user'), 'user_sessions', ['user_id'], unique=False)
    op.create_index(op.f('idx_user_sessions_token'), 'user_sessions', ['refresh_token_hash'], unique=False)
    op.drop_constraint(op.f('uq_simulation_results_attempt_id'), 'simulation_results', type_='unique')
    op.drop_constraint(op.f('uq_simulation_results_application_id'), 'simulation_results', type_='unique')
    op.create_unique_constraint(op.f('simulation_results_attempt_id_key'), 'simulation_results', ['attempt_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('simulation_results_application_id_key'), 'simulation_results', ['application_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('simulation_results', 'ai_dependency_score',
               existing_type=sa.NUMERIC(precision=3, scale=2),
               nullable=True,
               existing_server_default=sa.text('0.0'))
    op.drop_constraint(op.f('uq_reports_application_id'), 'reports', type_='unique')
    op.create_unique_constraint(op.f('reports_application_id_key'), 'reports', ['application_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('reports', 'recommendations',
               existing_type=sa.ARRAY(sa.String()),
               type_=postgresql.ARRAY(sa.TEXT()),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::text[]"))
    op.alter_column('reports', 'weaknesses',
               existing_type=sa.ARRAY(sa.String()),
               type_=postgresql.ARRAY(sa.TEXT()),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::text[]"))
    op.alter_column('reports', 'strengths',
               existing_type=sa.ARRAY(sa.String()),
               type_=postgresql.ARRAY(sa.TEXT()),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::text[]"))
    op.alter_column('reports', 'summary',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(op.f('uq_rankings_application_id'), 'rankings', type_='unique')
    op.create_unique_constraint(op.f('rankings_application_id_key'), 'rankings', ['application_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_rankings_top_candidates'), 'rankings', ['internship_id'], unique=False, postgresql_where='((is_top_candidate = true) AND (deleted_at IS NULL))')
    op.create_index(op.f('idx_rankings_internship_score'), 'rankings', ['internship_id', sa.literal_column('final_score DESC NULLS LAST')], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_index(op.f('idx_rankings_internship_rank'), 'rankings', ['internship_id', 'internship_rank'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_index(op.f('idx_notifications_user_unread'), 'notifications', ['user_id'], unique=False, postgresql_where='(is_read = false)')
    op.alter_column('notifications', 'message',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(op.f('uq_interview_results_session_id'), 'interview_results', type_='unique')
    op.drop_constraint(op.f('uq_interview_results_application_id'), 'interview_results', type_='unique')
    op.create_unique_constraint(op.f('interview_results_session_id_key'), 'interview_results', ['session_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('interview_results_application_id_key'), 'interview_results', ['application_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('interview_results', 'improvements',
               existing_type=sa.ARRAY(sa.String()),
               type_=postgresql.ARRAY(sa.TEXT()),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::text[]"))
    op.alter_column('interview_results', 'strengths',
               existing_type=sa.ARRAY(sa.String()),
               type_=postgresql.ARRAY(sa.TEXT()),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::text[]"))
    op.drop_constraint(op.f('fk_internships_updated_by_users'), 'internships', type_='foreignkey')
    op.drop_constraint(op.f('fk_internships_created_by_users'), 'internships', type_='foreignkey')
    op.create_index(op.f('idx_internships_company'), 'internships', ['company_id'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.alter_column('internships', 'technologies',
               existing_type=sa.ARRAY(sa.String()),
               type_=postgresql.ARRAY(sa.TEXT()),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::text[]"))
    op.alter_column('internships', 'required_skills',
               existing_type=sa.ARRAY(sa.String()),
               type_=postgresql.ARRAY(sa.TEXT()),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::text[]"))
    op.alter_column('internships', 'responsibilities',
               existing_type=sa.ARRAY(sa.String()),
               type_=postgresql.ARRAY(sa.TEXT()),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::text[]"))
    op.drop_column('internships', 'slug')
    op.drop_column('internships', 'updated_by')
    op.drop_column('internships', 'created_by')
    op.drop_column('internships', 'view_count')
    op.drop_column('internships', 'application_deadline')
    op.drop_column('internships', 'application_limit')
    op.drop_column('internships', 'openings')
    op.drop_column('internships', 'stipend_currency')
    op.drop_column('internships', 'stipend_max')
    op.drop_column('internships', 'stipend_min')
    op.drop_column('internships', 'duration_weeks')
    op.drop_column('internships', 'location')
    op.drop_column('internships', 'work_mode')
    op.drop_column('internships', 'published_at')
    op.drop_column('internships', 'status')
    op.drop_constraint(op.f('uq_integrity_results_application_id'), 'integrity_results', type_='unique')
    op.create_unique_constraint(op.f('integrity_results_application_id_key'), 'integrity_results', ['application_id'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(op.f('uq_dna_profiles_application_id'), 'dna_profiles', type_='unique')
    op.create_unique_constraint(op.f('dna_profiles_application_id_key'), 'dna_profiles', ['application_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_company_member'), 'company_members', ['company_id', 'user_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_company_members_user'), 'company_members', ['user_id'], unique=False)
    op.create_index(op.f('idx_company_members_company'), 'company_members', ['company_id'], unique=False)
    op.drop_constraint(op.f('uq_companies_name'), 'companies', type_='unique')
    op.create_index(op.f('uq_companies_name_active'), 'companies', ['name'], unique=True, postgresql_where='(deleted_at IS NULL)')
    op.create_index(op.f('idx_companies_created_by'), 'companies', ['created_by'], unique=False)
    op.create_unique_constraint(op.f('companies_name_key'), 'companies', ['name'], postgresql_nulls_not_distinct=False)
    op.alter_column('companies', 'description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_constraint(op.f('uq_candidate_mappings_simulation_candidate_id'), 'candidate_mappings', type_='unique')
    op.drop_constraint(op.f('uq_candidate_mappings_interview_candidate_uuid'), 'candidate_mappings', type_='unique')
    op.drop_constraint(op.f('uq_candidate_mappings_capvia_candidate_uuid'), 'candidate_mappings', type_='unique')
    op.drop_constraint(op.f('uq_candidate_mappings_ats_user_uuid'), 'candidate_mappings', type_='unique')
    op.create_index(op.f('idx_candidate_mappings_simulation'), 'candidate_mappings', ['simulation_candidate_id'], unique=False)
    op.create_unique_constraint(op.f('candidate_mappings_simulation_candidate_id_key'), 'candidate_mappings', ['simulation_candidate_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('candidate_mappings_interview_candidate_uuid_key'), 'candidate_mappings', ['interview_candidate_uuid'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('candidate_mappings_capvia_candidate_uuid_key'), 'candidate_mappings', ['capvia_candidate_uuid'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('candidate_mappings_ats_user_uuid_key'), 'candidate_mappings', ['ats_user_uuid'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(op.f('uq_ats_results_application_id'), 'ats_results', type_='unique')
    op.create_unique_constraint(op.f('ats_results_application_id_key'), 'ats_results', ['application_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('ats_results', 'fraud_probability',
               existing_type=sa.NUMERIC(precision=5, scale=4),
               nullable=True,
               existing_server_default=sa.text('0.0'))
    op.alter_column('ats_results', 'missing_skills',
               existing_type=sa.ARRAY(sa.String()),
               type_=postgresql.ARRAY(sa.TEXT()),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::text[]"))
    op.alter_column('ats_results', 'matched_skills',
               existing_type=sa.ARRAY(sa.String()),
               type_=postgresql.ARRAY(sa.TEXT()),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::text[]"))
    op.create_index(op.f('uq_candidate_vacancy_active'), 'applications', ['candidate_id', 'vacancy_id'], unique=True, postgresql_where='(deleted_at IS NULL)')
    op.create_index(op.f('idx_applications_vacancy'), 'applications', ['vacancy_id'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_index(op.f('idx_applications_status'), 'applications', ['status'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_index(op.f('idx_applications_candidate'), 'applications', ['candidate_id'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.drop_column('applications', 'rejection_reason')
    op.drop_column('applications', 'hired_at')
    op.drop_column('applications', 'withdrawn_at')
    op.drop_column('applications', 'resume_url')
    op.drop_column('applications', 'cover_letter')
    op.drop_constraint(op.f('uq_application_mappings_simulation_attempt_id'), 'application_mappings', type_='unique')
    op.drop_constraint(op.f('uq_application_mappings_simulation_application_id'), 'application_mappings', type_='unique')
    op.drop_constraint(op.f('uq_application_mappings_interview_session_uuid'), 'application_mappings', type_='unique')
    op.drop_constraint(op.f('uq_application_mappings_ats_resume_uuid'), 'application_mappings', type_='unique')
    op.drop_constraint(op.f('uq_application_mappings_application_id'), 'application_mappings', type_='unique')
    op.create_index(op.f('idx_application_mappings_attempt'), 'application_mappings', ['simulation_attempt_id'], unique=False)
    op.create_unique_constraint(op.f('application_mappings_simulation_attempt_id_key'), 'application_mappings', ['simulation_attempt_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('application_mappings_simulation_application_id_key'), 'application_mappings', ['simulation_application_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('application_mappings_interview_session_uuid_key'), 'application_mappings', ['interview_session_uuid'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('application_mappings_ats_resume_uuid_key'), 'application_mappings', ['ats_resume_uuid'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('application_mappings_application_id_key'), 'application_mappings', ['application_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('application_mappings', 'combined_risk_level',
               existing_type=postgresql.ENUM('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='risk_level'),
               nullable=True,
               existing_server_default=sa.text("'LOW'::risk_level"))
    op.alter_column('activity_logs', 'description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_table('application_events')
    # ### end Alembic commands ###
